services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - urbanfresh-network
  

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always  
    networks:
      - urbanfresh-network
    

  auth-service:
    build: 
      context: ../services/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001" 
    volumes:
      - ../services/auth-service:/app
      - /app/node_modules
    env_file: 
      - ../services/auth-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - urbanfresh-network


  api-gateway:
    build: 
      context: ../services/api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    restart: always
    env_file: 
      - ../services/api-gateway/.env
    ports: 
      - "8000:8000"
    volumes:
      - ../services/api-gateway:/app
      - /app/node_modules  
    depends_on: 
      - auth-service
    networks:
      - urbanfresh-network     


  store-service:
    build: 
      context: ../services/store-service
      dockerfile: Dockerfile.dev
    container_name:  store-service
    restart: always
    env_file:
      - ../services/store-service/.env
    ports:
      - "4003:4003"
    volumes:
      - ../services/store-service:/app
      - ./store-service/uploads:/app/uploads
      - /app/node_modules  
    depends_on:
      - mongodb  
    networks:
      - urbanfresh-network     


  product-service:
    build:
      context: ../services/product-service
      dockerfile: Dockerfile.dev
    container_name: product-service   
    restart: always
    volumes:
      - ../services/product-service:/app
      - /app/node_modules
    env_file:
      - ../services/product-service/.env  
    ports:
      - "4002:4002"
    depends_on:
      - mongodb
    networks:
      - urbanfresh-network


volumes:
  mongo_data:

networks:
  urbanfresh-network:
    driver: bridge
    



























































    