services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always  
    networks:
      - urbanfresh-network
    

  auth-service:
    build: 
      context: ../services/auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001" 
    volumes:
      - ../services/auth-service:/app
      - /app/node_modules
    env_file: 
      - ../services/auth-service/.env
    depends_on:
      - redis
    networks:
      - urbanfresh-network

  blog-service:
    build:
      context: ../services/blog-service
      dockerfile: Dockerfile.dev
    container_name: blog-service
    restart: always
    ports:
      - "3004:3004"
    volumes:
      - ../services/blog-service:/app
      - /app/node_modules
    env_file:
      - ../services/blog-service/.env
    networks:
      - urbanfresh-network


  api-gateway:
    build: 
      context: ../services/api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    restart: always
    env_file: 
      - ../services/api-gateway/.env
    ports: 
      - "8000:8000"
    volumes:
      - ../services/api-gateway:/app
      - /app/node_modules  
    depends_on: 
      - auth-service
      - blog-service
    networks:
      - urbanfresh-network     

networks:
  urbanfresh-network:
    driver: bridge
    



























































    
